from . import remote_server
from . import res_partner
from . import client_data
from . import account_move
from . import account_payment
from . import balance_history
from . import product_template
from . import sale_order
from . import res_users
from . import res_company
